name: CI
on:
    push:
        branches:
            - main
jobs:
    install-and-test:
        name: Install dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install
    build-android:
        name: Build app
        needs: install-and-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install
            - name: Build Android Release
              run: |
                  cd android && chmod +x ./gradlew assembleRelease
